In [1]:
from TTS.api import TTS

print("TTS library loaded successfully")

c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

TTS library loaded successfully

In [2]:
from TTS.api import TTS

tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2")

print("XTTS v2 loaded successfully")

XTTS v2 loaded successfully

In [3]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/timit_metadata.csv"
)

df.head()

,audio_path,speaker_id,dialect,split,utterance_id,transcript,duration,sample_rate
0,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...,FBCG1,DR8,train,SA1,She had your dark suit in greasy wash water al...,3.091250,16000
1,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...,FBCG1,DR8,train,SA2,Don't ask me to carry an oily rag like that.,3.654437,16000
2,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...,FBCG1,DR8,train,SI1612,"They've never met, you know.",1.497625,16000
3,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...,FBCG1,DR8,train,SI2242,Twenty-two or twenty-three.,2.080000,16000
4,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...,FBCG1,DR8,train,SI982,Tetanus could be avoided by pouring warm turpe...,3.993625,16000

In [4]:
speaker_id = "FBCG1"

speaker_data = df[
    df["speaker_id"] == speaker_id
]

speaker_data[
    [
        "speaker_id",
        "utterance_id",
        "transcript",
        "duration",
        "audio_path"
    ]
]

,speaker_id,utterance_id,transcript,duration,audio_path
0,FBCG1,SA1,She had your dark suit in greasy wash water al...,3.091250,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
1,FBCG1,SA2,Don't ask me to carry an oily rag like that.,3.654437,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
2,FBCG1,SI1612,"They've never met, you know.",1.497625,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
3,FBCG1,SI2242,Twenty-two or twenty-three.,2.080000,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
4,FBCG1,SI982,Tetanus could be avoided by pouring warm turpe...,3.993625,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
5,FBCG1,SX172,The triumphant warrior exhibited naive heroism.,3.212813,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
6,FBCG1,SX262,Can the agency overthrow alien forces?,2.604812,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
7,FBCG1,SX352,"According to my interpretation of the problem,...",4.326437,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
8,FBCG1,SX442,Suburban housewives often suffer from the gab ...,3.596812,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...
9,FBCG1,SX82,Good service should be rewarded by big tips.,2.572812,data\raw\timit\data\lisa\data\timit\raw\TIMIT\...

In [5]:
reference = speaker_data.iloc[0]

reference_audio = reference["audio_path"]

print("Speaker:", reference["speaker_id"])
print("Reference:", reference_audio)
print("Transcript:", reference["transcript"])

Speaker: FBCG1
Reference: data\raw\timit\data\lisa\data\timit\raw\TIMIT\TRAIN\DR8\FBCG1\SA1.WAV
Transcript: She had your dark suit in greasy wash water all year.

In [6]:
text = "This is my first voice cloning experiment."

In [8]:
output_path = "../data/generated/xtts_first_test.wav"

tts.tts_to_file(
    text=text,
    speaker_wav=reference_audio,
    language="en",
    file_path=output_path
)

print("Generated:", output_path)

RuntimeError: Failed to create AudioDecoder for data\raw\timit\data\lisa\data\timit\raw\TIMIT\TRAIN\DR8\FBCG1\SA1.WAV: Could not load libtorchcodec. Likely causes:
          1. FFmpeg is not properly installed in your environment. We support
             versions 4, 5, 6, 7, 8, and 9, and we attempt to load libtorchcodec
             for each of those versions. Errors for versions not installed on
             your system are expected; only the error for your installed FFmpeg
             version is relevant. On Windows, ensure you've installed the
             "full-shared" version which ships DLLs.
          2. The PyTorch version (2.13.0+cpu) is not compatible with
             this version of TorchCodec. Refer to the version compatibility
             table:
             https://github.com/pytorch/torchcodec?tab=readme-ov-file#installing-torchcodec.
          3. Another runtime dependency; see exceptions below.

        The following exceptions were raised as we tried to load libtorchcodec:

[start of libtorchcodec loading traceback]
FFmpeg version 9:
Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1516, in load_library
    ctypes.CDLL(path)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 433, in __init__
    self._handle = self._load_library(name, mode, handle, winmode)
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 451, in _load_library
    return _LoadLibrary(self._name, winmode)
FileNotFoundError: Could not find module 'C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core9.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 132, in load_core_libraries
    torch.ops.load_library(core_library_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1518, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core9.dll

FFmpeg version 8:
Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1516, in load_library
    ctypes.CDLL(path)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 433, in __init__
    self._handle = self._load_library(name, mode, handle, winmode)
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 451, in _load_library
    return _LoadLibrary(self._name, winmode)
FileNotFoundError: Could not find module 'C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core8.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 132, in load_core_libraries
    torch.ops.load_library(core_library_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1518, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core8.dll

FFmpeg version 7:
Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1516, in load_library
    ctypes.CDLL(path)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 433, in __init__
    self._handle = self._load_library(name, mode, handle, winmode)
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 451, in _load_library
    return _LoadLibrary(self._name, winmode)
FileNotFoundError: Could not find module 'C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core7.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 132, in load_core_libraries
    torch.ops.load_library(core_library_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1518, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core7.dll

FFmpeg version 6:
Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1516, in load_library
    ctypes.CDLL(path)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 433, in __init__
    self._handle = self._load_library(name, mode, handle, winmode)
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 451, in _load_library
    return _LoadLibrary(self._name, winmode)
FileNotFoundError: Could not find module 'C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core6.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 132, in load_core_libraries
    torch.ops.load_library(core_library_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1518, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core6.dll

FFmpeg version 5:
Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1516, in load_library
    ctypes.CDLL(path)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 433, in __init__
    self._handle = self._load_library(name, mode, handle, winmode)
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 451, in _load_library
    return _LoadLibrary(self._name, winmode)
FileNotFoundError: Could not find module 'C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core5.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 132, in load_core_libraries
    torch.ops.load_library(core_library_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1518, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core5.dll

FFmpeg version 4:
Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1516, in load_library
    ctypes.CDLL(path)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 433, in __init__
    self._handle = self._load_library(name, mode, handle, winmode)
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmayu\AppData\Local\Programs\Python\Python314\Lib\ctypes\__init__.py", line 451, in _load_library
    return _LoadLibrary(self._name, winmode)
FileNotFoundError: Could not find module 'C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core4.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 132, in load_core_libraries
    torch.ops.load_library(core_library_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torch\_ops.py", line 1518, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\pmayu\OneDrive\Documents\Rinal data Science\Apziva\Voice-Cloning-Fake-Audio-Detection\venv\Lib\site-packages\torchcodec\libtorchcodec_core4.dll
[end of libtorchcodec loading traceback].